// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PVScan.Desktop.WPF.Services.SQLiteEncrypted;

namespace PVScan.Desktop.WPF.Services.SQLiteEncrypted.Migrations
{
    [DbContext(typeof(SQLiteEncryptedDbContext))]
    partial class SQLiteEncryptedDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("PVScan.Desktop.WPF.Models.SQLiteEncrypedKVP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("KVPs");
                });
#pragma warning restore 612, 618
        }
    }
}
