// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PVScan.EntityFramework;

namespace PVScan.EntityFramework.Migrations
{
    [DbContext(typeof(PVScanDbContext))]
    partial class PVScanDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("PVScan.Domain.Models.Barcode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<byte[]>("Bytes")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Format")
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ScannedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ScannedByEmail")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ScannedByEmail");

                    b.ToTable("Barcodes");
                });

            modelBuilder.Entity("PVScan.Domain.Models.User", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Email");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PVScan.Domain.Models.Barcode", b =>
                {
                    b.HasOne("PVScan.Domain.Models.User", "ScannedBy")
                        .WithMany("Barcodes")
                        .HasForeignKey("ScannedByEmail");

                    b.OwnsOne("PVScan.Domain.Models.Coordinate", "Location", b1 =>
                        {
                            b1.Property<int>("BarcodeId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .UseIdentityColumn();

                            b1.Property<double>("Latitude")
                                .HasColumnType("float");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float");

                            b1.HasKey("BarcodeId");

                            b1.ToTable("Barcodes");

                            b1.WithOwner()
                                .HasForeignKey("BarcodeId");
                        });

                    b.Navigation("Location");

                    b.Navigation("ScannedBy");
                });

            modelBuilder.Entity("PVScan.Domain.Models.User", b =>
                {
                    b.Navigation("Barcodes");
                });
#pragma warning restore 612, 618
        }
    }
}
